combo works b4 =, combo doesnt work after =
eg 1+2+3-2= works
eg 90-50+4= works
eg 90-50=+8 doesn't work
because after each addition i reset
java.lang.NumberFormatException: For input string: ""